version: 0.2
phases:
  install:
    commands:
      # - curl -fsSL https://get.docker.com -o get-docker.sh
      # - sudo sh get-docker.sh
      # - sudo apt-get install docker-compose -y
      # - sudo service docker start
  build:
    commands:
      - sudo sh build.sh
      - sudo sh rm.sh
      - docker images
      - sudo apt install awscli -y

  post_build: 
    commands:
      # - sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 877969058937.dkr.ecr.us-east-1.amazonaws.com
      # - sudo docker tag nod 877969058937.dkr.ecr.us-east-1.amazonaws.com/nirmal_nod:latest
      # - sudo docker push 877969058937.dkr.ecr.us-east-1.amazonaws.com/nirmal_nod:latest
      - sudo aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws/p3t0m4x7
      - sudo docker tag mysq public.ecr.aws/p3t0m4x7/dock_task_mysql:latest
      - sudo docker push public.ecr.aws/p3t0m4x7/dock_task_mysql:latest