version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sudo sh get-docker.sh
      - sudo apt-get install docker-compose -y
  build:
    commands:
      - sudo sh build.sh
      - sudo sh rm.sh
      - docker images